name: ChampionshipsBingoWorker
version: '${project.version}'
main: ink.ziip.championshipscore.worker.BingoWorkerPlugin
api-version: '26.1'
folia-supported: true
authors: [ Eter Lu, LettuceIce ]
description: Dedicated Folia execution worker for ChampionshipsCore Bingo matches.
softdepend:
  - PlaceholderAPI
