name: ChampionshipsCore
version: '${project.version}'
main: ink.ziip.championshipscore.ChampionshipsCore
api-version: '1.21'
authors: [ Eter Lu, LettuceIce ]
depend:
  - ProtocolLib
  - PlaceholderAPI
  - FastAsyncWorldEdit
softdepend:
  - PhantomWorlds
  - BingoReloaded
commands:
  cc:
    description: Core command.
    usage: /<command>
